fragment PostParts on Post {
  title
  heroImg
  excerpt
  author {
    ... on Document {
      id
    }
  }
  _body
}

fragment GlobalParts on Global {
  header {
    __typename
    icon {
      __typename
      color
      style
      name
    }
    color
    nav {
      __typename
      href
      label
    }
    areas {
      __typename
      href
      label
      icon {
        __typename
        color
        style
        name
      }
      description
      comingSoon
    }
    resources {
      __typename
      href
      label
      icon {
        __typename
        color
        style
        name
      }
      description
    }
  }
  footer {
    __typename
    color
    social {
      __typename
      map
      facebook
      twitter
      linkedin
      github
    }
  }
  theme {
    __typename
    color
    font
    icon
  }
}

fragment AuthorParts on Author {
  name
  avatar
}

fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      tagline
      headline
      text
      actions {
        __typename
        label
        type
        icon
        link
      }
      image {
        __typename
        src
        alt
      }
      color
    }
    ... on PageBlocksFeatures {
      items {
        __typename
        icon {
          __typename
          color
          style
          name
        }
        title
        link
        text
      }
      color
    }
    ... on PageBlocksFeaturesAlt {
      items {
        __typename
        icon {
          __typename
          color
          style
          name
        }
        title
        link
        comingSoon
        text
      }
      color
    }
    ... on PageBlocksFeaturesAlt2 {
      items {
        __typename
        icon {
          __typename
          color
          style
          name
        }
        title
        link
        text
      }
      color
    }
    ... on PageBlocksCardGrid2 {
      items {
        __typename
        title
        image
        link
        text
      }
      color
    }
    ... on PageBlocksContent {
      body
      color
    }
    ... on PageBlocksTestimonial {
      quote
      author
      color
    }
  }
}

fragment AreaParts on Area {
  title
  heroImg
  excerpt
  author {
    ... on Document {
      id
    }
  }
  date
  _body
}
